# Generated by Django 4.2.2 on 2025-03-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Email', models.EmailField(blank=True, default='', max_length=300)),
                ('Username', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
