# Generated by Django 4.2.2 on 2025-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_profiles_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Title',
            field=models.CharField(blank=True, choices=[('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], max_length=5),
        ),
    ]
