# Generated by Django 4.2.2 on 2025-03-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=5)),
                ('First_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Email', models.EmailField(blank=True, default='', max_length=300)),
                ('Username', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
