# Generated by Django 4.2.2 on 2025-03-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Title',
            field=models.CharField(blank=True, choices=[('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mr', 'Mr')], max_length=5),
        ),
    ]
